import Images from "../assets/images/images";

const CoffeeList = [
  {
    id: 1,
    category: "Americano",
    product: "Americano",
    description: "description about the coffee/bean",
    img: Images.americano_pic_1_square(),
    price: 2.99,
  },
  {
    id: 2,
    category: "Americano",
    product: "Americano",
    description: "description about the coffee/bean",
    img: Images.americano_pic_2_square(),
    price: 2.99,
  },
  {
    id: 3,
    category: "Americano",
    product: "Americano",
    description: "description about the coffee/bean",
    img: Images.americano_pic_3_square(),
    price: 2.99,
  },
  {
    id: 4,
    category: "black coffee",
    product: "Black Coffee",
    description: "description about the coffee/bean",
    img: Images.black_coffee_pic_1_square(),
    price: 2.99,
  },
  {
    id: 5,
    category: "black coffee",
    product: "Black Coffee",
    description: "description about the coffee/bean",
    img: Images.black_coffee_pic_2_square(),
    price: 2.99,
  },
  {
    id: 6,
    category: "black coffee",
    product: "Black Coffee",
    description: "description about the coffee/bean",
    img: Images.black_coffee_pic_3_square(),
    price: 2.99,
  },
  {
    id: 7,
    category: "cappuccino",
    product: "Cappuccino",
    description: "description about the coffee/bean",
    img: Images.cappuccino_pic_1_square(),
    price: 2.99,
  },
  {
    id: 8,
    category: "cappuccino",
    product: "Cappuccino",
    description: "description about the coffee/bean",
    img: Images.cappuccino_pic_2_square(),
    price: 2.99,
  },
  {
    id: 9,
    category: "cappuccino",
    product: "Cappuccino",
    description: "description about the coffee/bean",
    img: Images.cappuccino_pic_3_square(),
    price: 2.99,
  },
  {
    id: 10,
    category: "espresso",
    product: "espresso",
    description: "description about the coffee/bean",
    img: Images.espresso_pic_1_square(),
    price: 2.99,
  },
  {
    id: 11,
    category: "espresso",
    product: "espresso",
    description: "description about the coffee/bean",
    img: Images.espresso_pic_2_square(),
    price: 2.99,
  },
  {
    id: 12,
    category: "espresso",
    product: "espresso",
    description: "description about the coffee/bean",
    img: Images.espresso_pic_3_square(),
    price: 2.99,
  },
  {
    id: 13,
    category: "latte",
    product: "latte",
    description: "description about the coffee/bean",
    img: Images.latte_pic_1_square(),
    price: 2.99,
  },
  {
    id: 14,
    category: "latte",
    product: "latte",
    description: "description about the coffee/bean",
    img: Images.latte_pic_1_square(),
    price: 2.99,
  },
  {
    id: 15,
    category: "latte",
    product: "latte",
    description: "description about the coffee/bean",
    img: Images.latte_pic_1_square(),
    price: 2.99,
  },
  {
    id: 16,
    category: "macchiato",
    product: "Macchiato",
    description: "description about the coffee/bean",
    img: Images.macchiato_pic_1_square(),
    price: 2.99,
  },
  {
    id: 17,
    category: "macchiato",
    product: "Macchiato",
    description: "description about the coffee/bean",
    img: Images.macchiato_pic_2_square(),
    price: 2.99,
  },
  {
    id: 18,
    category: "macchiato",
    product: "Macchiato",
    description: "description about the coffee/bean",
    img: Images.macchiato_pic_3_square(),
    price: 2.99,
  },
];

export default CoffeeList;
